server:
  port: 16000

retry-config:
  initial-interval-ms: 1000
  max-interval-ms: 10000
  multiplier: 2.0
  maxAttempts: 3
  sleep-time-ms: 2000

kafka-config:
  bootstrap-servers: localhost:19092, localhost:29092, localhost:39092
  schema-registry-url-key: schema.registry.url
  schema-registry-url: http://localhost:8081
  topic-name: send-email-topic
  topic-names-to-create:
    - send-email-topic
    - send-email-topic
  num-of-partitions: 3
  replication-factor: 3
